dominio = "suaempresa.sankhyacloud.com.br"
codigo_autorizacao = ""
top_orcamento = "3000"
top_pedido = "1411"
top_venda_nfe = "1202"
top_nfe_triangular = "1422"
codigo_empresa_padrao = "1"

# Atalhos pros nomes dos conferentes
# Estes nomes popularão o campo "AD_CONFERENTE" dos documentos.
# As colunas "AD_CONFERENTE" e "AD_HORARIO_CONFERENCIA" devem estar
# presentes na tabela "TGFCAB" para que conferentes possam ser
# especificados nos documentos.
[conferentes]
# j="JOÃO"
# l="LUDGERSON"

# Atalhos pros nomes dos separadores
# Estes nomes popularão o campo "AD_SEPARADOR" dos documentos.
# As colunas "AD_SEPARADOR" e "AD_HORARIO_SEPARACAO" devem estar
# presentes na tabela "TGFCAB" para que separadores possam ser
# especificados nos documentos.
[separadores]
# ro="RODRIGO"
# d="DENILSON"

[faturamento]
campo_tipo_entrega="AD_TIPOENTREGA" 
# Ao faturar pedidos com o AD_TIPOENTREGA igual a "TRANSPORTADORA" ou
# igual a "ENTREGA", etiquetas serão impressas. 
emitir_etiquetas=["TRANPORTADORA", "ENTREGA"]
# Pedidos com AD_TIPOENTREGA igual a "TRANSPORTADORA"
# devem ter uma transportadora para poderem ser faturados.
sempre_tem_transportadora=["TRANSPORTADORA"]
